apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: loadrkqh4407-tenant-component
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: loadrkqh4407-tenant-component
    app.kubernetes.io/part-of: loadrkqh4407-tenant-app
  name: loadrkqh4407-tenant-component
  namespace: loadrkqh4407-tenant
spec:
  path: /
  port:
    targetPort: 8081
  to:
    kind: Service
    name: loadrkqh4407-tenant-component
    weight: null
status: {}
